# Generated by Django 5.1.3 on 2026-01-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='companys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companys.companys'),
            preserve_default=False,
        ),
    ]
